var personajes = [
  {
    name: 'Superman',
    num:'0',
    photo:
    [{'img':'https://static.vix.com/es/sites/default/files/styles/large/public/btg/cine.batanga.com/files/rumor-doomsday-batman-v-superman-dawn-of-justice-2.jpg?itok=qgzF5wDk',
      'texto':'Batman v Superman: Dawn of Justice'},
     {'img':'http://cdn.collider.com/wp-content/uploads/2016/06/superman-returns-brandon-routh.jpg',
      'texto':'Superman Returns'},
     {'img':'http://1.bp.blogspot.com/-pMNdOg7HnLs/UZpw9tz_5uI/AAAAAAAAAmY/fZRPSjTnndc/s1600/dc_comics_superman_christopher_reeve_desktop_1024x768_wallpaper-1073650.png',
      'texto':'Superman'},
     {'img':'http://www.asset1.net/tv/pictures/movie/superman-ii-1980/superman-II-DI.jpg',
      'texto':'Superman II'},
     {'img':'http://static1.squarespace.com/static/51b3dc8ee4b051b96ceb10de/51ce6099e4b0d911b4489b79/564f5cb7e4b0bbb1d9cb60ed/1448042558764/?format=1000w',
      'texto':' Superman III'},
     {'img':'http://dreamers.com/indices/imagenes/peliculas.6640.IMAGEN5.jpg',
      'texto':'Superman IV: The Quest for Peace'},
     {'img':'https://i.ytimg.com/vi/wV6pB5g3STA/hqdefault.jpg',
      'texto':'Superman/Batman: Apocalypse'},
     {'img':'https://image.tmdb.org/t/p/w1280/7saKPnFb2sispqFomMM9NL4Auy2.jpg',
      'texto':'Superman/Batman: Public Enemies'}
    ],
    caracteristica:'Superman, cuyo nombre Kryptoniano es Kal-EI y su nombre terrestre es Clark Kent.',
    curiosidad:
    [{'Información':'Superman: The Movie, se vio por primera vez la aparición cinematográfica de dicho personaje. Casi 20 años más tarde, se vió una actualización del traje. En 2013, en Man of Steel, se diseñó un nueov traje que rompe con todos los esquemas.',
      'Foto':'http://1.bp.blogspot.com/-A63C-LcpnFI/UMynT-h_RJI/AAAAAAAAVio/5PYzxYKAyb0/s1600/3COST.JPG'},
     {'Información':'Man of Steel, se puede apreciar un cambio radical en el tono azul, confeccionado de en un material con aspecto más plástico. El patrón es claramente una cota de malla medieval',
       'Foto':'http://2.bp.blogspot.com/-y9BB1IpMetg/UMyj5W8ItuI/AAAAAAAAVg0/2weKTTmzX88/s1600/CAVSUPSUITCOMP+%282%29.jpg'},
     {'Información':'Superman Returns, se puede apreciar un escudo pequeño, tridimensional y pegado al traje, el rojo es casi amarronado',
      'Foto':'http://2.bp.blogspot.com/-FEvipr93Ua0/UMyi_MPmULI/AAAAAAAAVf0/9h-FakQ-uZA/s1600/ROUTHCOSTS.JPG'},
     {'Información':'Superman: The Movie no podía dejar de lado el calzón, que en esta versión era ancho y también de material elástico como el traje',
      'Foto':'http://3.bp.blogspot.com/-Ai8qnzvgLUo/UMyiAjqpypI/AAAAAAAAVfo/Z6k6_JBOrOE/s1600/reevecostcomp.JPG'},
    ],
  },
  {
    name: 'Wonder Woman',
    num:'1',
    photo:
    [{'img':'http://photos1.blogger.com/blogger/4167/3097/1600/mulemaravila.jpg',
      'texto':'Wonder Woman: Balance of Power'},
     {'img':'https://images-na.ssl-images-amazon.com/images/M/MV5BYzRlNzYwYWEtYjMxNi00ZDQzLTk1ZTItODg1NTU1M2RlZTE3XkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SY500_SX333_AL_.jpg',
      'texto':'Wonder Woman 2013'},
     {'img':'http://manapop.com/wp-content/uploads/2016/12/vlcsnap-2016-11-15-22h22m28s946.png',
      'texto':'Wonder Woman: Whos Afraid of Diana Prince? 1967'},
     {'img':'http://mouse.latercera.com/wp-content/uploads/2017/05/crosby.jpg',
      'texto':'Wonder Woman 1974'},
     {'img':'https://images-na.ssl-images-amazon.com/images/M/MV5BYmE0OTljMTItMWZiNi00YTcxLWFiYmQtY2Y5YmE4YjQwNTM3XkEyXkFqcGdeQXVyMTU2MjI3NTk@._V1_.jpg',
      'texto':'Wonder Woman 2011'},
     {'img':'http://images3.static-bluray.com/products/20/17399_4_large.jpg',
      'texto':'Wonder Woman 1975–1979'},
     {'img':'https://upload.wikimedia.org/wikipedia/en/thumb/a/af/WWPoster.jpg/220px-WWPoster.jpg',
      'texto':'Wonder Woman 2009'},
     {'img':'https://i.ytimg.com/vi/38JK02f0zr0/maxresdefault.jpg',
      'texto':' Wonder Woman 2017'}
    ],
    caracteristica:'creada por el psicólogo estadounidense William Moulton Marston bajo el seudónimo de Charles Moulton. Marston tomó como modelos a Elizabeth (Sadie) Holloway Marston, su esposa, y a Olive Byrne, con quien vivían en una relación de a tres.',
    curiosidad:
    [{'Información':'A lo largo de las apariciones cinematogrpaficas, de Wonder Woman, se puede apreciar un cambio radiacal en el vestuario',
      'Foto':'https://i.ytimg.com/vi/wBBr9CO0MP8/maxresdefault.jpg'},
     {'Información':'Lynda Carter protagonizó la serie de 1975, que ofreció una aproximación muy similar al vestuario de los cómics y una toma mucho más fiel en su origen y antecedentes',
      'Foto':'http://sm.ign.com/t/ign_latam/screenshot/t/the-third-/the-third-time-was-the-charm-for-wonder-womans-live-action-t_f3c8.1920.jpg'},
     {'Información':'En Wonder WOman 2013, su traje está bastante apegado al material fuente, aunque con las piernas completamente cubiertas.',
      'Foto':'http://4.bp.blogspot.com/-Zobavg2OYNY/UkHHk7rZrkI/AAAAAAAAFpo/BSQh-TwBvWI/s1600/adrianne-palicki-wonder-woman2.jpgSu'},
     {'Información':'Su último vestuario, en Wonder Woman 2017, es una reminiscencia de los cómics en su diseño general y esquema de color, pero también es claramente un traje de armadura rugosa.',
      'Foto':'https://pmcvariety.files.wordpress.com/2016/11/wonder-woman-trailer.jpg?w=1000&h=563&crop=1'}
    ],
  },

  {
    name: 'Batman',
    num: '2',
    photo:
    [{'img':'http://www.lascosasquenoshacenfelices.com/wp-content/uploads/2015/11/batman-under-the-red-hood-4ffb8aec0dd1b-1280x720.jpg',
      'texto':'Batman: Under the Red Hood'},
     {'img':'http://assets1.ignimgs.com/2017/02/04/legobatmanmovie-1280-2-1486205402178_1280w.jpg',
      'texto':'The LEGO Batman Movie  '},
     {'img':'https://nerdist.com/wp-content/uploads/2017/10/BTAS.jpg',
      'texto':'Batman: The Animated Series'},
     {'img':'https://robsmovievault.files.wordpress.com/2012/03/robin_batman1966.jpg',
      'texto':'Batman & Robin'},
     {'img':'http://cdn1us.denofgeek.com/sites/denofgeekus/files/bf-codpieces.jpg',
      'texto':'Batman Forever'},
     {'img':'https://i1.wp.com/xn--oo-yjab.cl/wp-content/uploads/2016/04/batman-returns-0.jpg?fit=372%2C498&ssl=1',
      'texto':'Batman Returns'},
     {'img':'https://i.redd.it/vzgcnlh3x1wz.jpg',
      'texto':'Batman v Superman: Dawn of Justice'},
     {'img':'https://gothamtrending.files.wordpress.com/2011/12/the-dark-knight-rises-stills-batman-christian-bale-batsuit-detail.jpg',
      'texto':'Batman Begins'}
    ],
    caracteristica:'La identidad conocida de Batman es Bruce Wayne, un hombre de negocios exitoso que vive en Ciudad Gótica.',
    curiosidad:
    [{'Información':'A lo largo de las apariciones cinematográficas, Batman ha ido mejorando su vesturio',
      'Foto':'http://laprimeraplana.com.mx/wp-content/uploads/2012/07/BATMAN-PORTADA-605x300.jpg'},
     {'Información':'LOS BAT-PEZONES, aparecieron en Batman Forever, de completo negro, sin florituras en los detalles y sin poder girar el cuello',
      'Foto':'http://img.europapress.es/fotoweb/fotonoticia_20160324110650-16031646499_9999.jpg?_ga=2.248491087.912893484.1516273917-456543890.1516273917'},
     {'Información':'Batman y Robin, Batman y Robin',
      'Foto':'http://img.europapress.es/fotoweb/fotonoticia_20160324110650-16031646579_9999.jpg?_ga=2.71191128.912893484.1516273917-456543890.1516273917'},
     {'Información':'Batman Begins: se presentó con un traje que en realidad era un prototipo de armadura de combate rechazado por el ejército, incluyó varios gadgets y una capa con tela con memoria, pintada de negro, con el símbolo del murciélogo en el pecho',
      'Foto':'http://i53.tinypic.com/2dj6ro4.jpg'}
    ],
  },

  {
    name: 'Flash',
    num: '3',
    photo:
    [{'img':'https://media.baselineresearch.com/images/228837/228837_full.jpg',
      'texto':'Flash Gordon'},
     {'img':'http://www.syfy.com/sites/syfy/files/wire/legacy/five-things-that-should-happen-in-the-flash-season-2-432033.jpg',
      'texto':'The Flash'},
     {'img':'http://contenidos.enter.co/custom/uploads/2017/07/the-flash-3840x2160-justice-league-hd-2017-6892.jpg',
      'texto':'Flash Point'}
    ],
    caracteristica:'Flash, es un superhéroe de la compañía estadounidense DC Comics que posee una velocidad sobrehumana, que incluye la habilidad de correr a gran velocidad, reflejos sobrehumanos y la capacidad de violar algunas leyes de la física.',
    curiosidad:
    [{'Información':'Mucho tiempo ha pasado desde que, en 1940, debutó en DC Comics un superhéroe con el alias de The Flash que tenía el maravilloso superpoder de correr a velocidades supersónicas.',
      'Foto':'https://i.ytimg.com/vi/JIEV8Cfgt6o/maxresdefault.jpg'},
     {'Información':'The Flash de Bruce Timm, sería un regreso a las raíces, casi idéntico al del superhéroe en la Edad de plata',
      'Foto':'https://static.vix.com/es/sites/default/files/styles/large/public/btg/the-flash-mortal-kombat-vs-dc-universe-videojuego.jpg?itok=VBW0pHC3'},
     {'Información':'The Flash en Injustice: Gods Among Us, aparece con un traje que se asemeja más a una armadura y que, si bien tiene los colores y tonalidades habituales, incluye una mayor sofisticación en los pequeños detalles y en la cantidad de piezas y accesorios.',
      'Foto':'https://static.vix.com/es/sites/default/files/styles/large/public/btg/the-flash-grant-gustin.jpg?itok=t1vab2vH'}
    ],
  },
];
console.log(personajes)
